language: php
php:
- 5.5
 
install:
- composer require yzalis/identicon
   
services: mysql
before_install:
- sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('rootman') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
- mysql -e 'CREATE DATABASE IF NOT EXISTS dbsoft806assignment1'
- mysql -u "root" -p"rootman" dbsoft806assignment1 < db.sql
- composer install

script:
- ./vendor/bin/phpunit