language: php
php:
- 7.0
 
install:
- composer require yzalis/identicon
   
services: mysql
before_install:
- mysql -e 'CREATE DATABASE IF NOT EXISTS dbsoft806assignment1'
- mysql -u "root" dbsoft806assignment1 < db.sql
- composer install
